name: Daily Question

on:
  schedule:
    - cron: "0 8 * * *" # Run at 9:30 AM CET

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  daily-question:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js

      - name: Commit changes
        run: |
          git config --global user.email "lazar.kulasevic@gmail.com"
          git config --global user.name "Actions Bot"
          git add -A
          git commit -m "index update"
          git push
