name: Daily Question

on:
  schedule:
    - cron: "30 8 * * *" # Run at 9:30 AM CET

jobs:
  daily-question:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run script
        run: node index.js
